{% set name = "pyfab" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyfab-{{ version }}.tar.gz
  sha256: c0cad0b5485ac020114f3e4af2aa1a227a2bcd2f803739d3b0c4838ad4bc913f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fslpy
    - nibabel
    - numpy
    - python >=3.7
    - six

test:
  imports:
    - fabber
    - fabber.test

about:
  home: https://fabber_core.readthedocs.io/
  summary: Python interface to the Fabber toolkit for Bayesian model fitting
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mcraig-ibme
